### ISSUE TITLE
Plugin Documentation

### ISSUE THREAD

**Issue by OPARA-PROSPER** [MLH-Fellowship/0.0.1-Oh-My-Dev#4]
@Oghenebrume50 @AlbertoPdRF I'm currently having a blocker setting up oh-my-zsh locally.

I'll be willing to write documentation for the plugin if i'm not able to successfully complete setup before deadline.

I'm making progress with setup though, I successfully upgraded my windows to enable me setup WSL (Windows Subsystem for Linux)

**Comment by AlbertoPdRF** [comment]
Installing it for WSL2 is a breeze, let me know if you have any problems with it and I'll try to help!

**Comment by Oghenebrume50** [comment]
@OPARA-PROSPER yeah man that is understandable, I guess this will come in once we start getting features running in
