### ISSUE TITLE
Articles JSON output Formatting

### ISSUE THREAD

**Issue by OPARA-PROSPER** [MLH-Fellowship/0.0.1-Oh-My-Dev#7]
@AlbertoPdRF @Oghenebrume50

**Comment by Oghenebrume50** [comment]
@AlbertoPdRF so how do you suggest we make this output?

**Comment by AlbertoPdRF** [comment]
As a JSON isn't really that nice to read, I would just pick up from it the information we want to show to the user and display that instead, in the best way we can. I haven't though which that information should be, but an example to illustrate what I said could be:

```sh
Title
Posted on date by user

Content
```

**Comment by Oghenebrume50** [comment]
So we loop through the returned data and extra this information, make sense. 
There is no ```content``` key in the object though, it is basically a URL to the article itself 

Maybe we could output 
```description```
```url```

So the user just clicks on the URL and the article opens up in their default browser

**Comment by AlbertoPdRF** [comment]
Yeah, the `content` was just an example to illustrate what I meant, not an actual key.

Outputting the `url` too sounds goot to me. We should also present only one article at a time to the user, and offer some way to navigate through them, no? Like, for instance, only output the last one and let the user choose if they want to see the next one or not.

**Comment by OPARA-PROSPER** [comment]
> Outputting the `url` too sounds goot to me. We should also present only one article at a time to the user, and offer some way to navigate through them, no? Like, for instance, only output the last one and let the user choose if they want to see the next one or not.

Makes sense

Probably a `view more [Y] [N]` prompt
