### ISSUE TITLE
Turn the script into an actual plugin.

### ISSUE THREAD

**Issue by AlbertoPdRF** [MLH-Fellowship/0.0.1-Oh-My-Dev#9]
In order to do this, [this line](https://github.com/MLH-Fellowship/0.0.1-Oh-My-Dev/blob/master/oh-my-dev.plugin.zsh#L16) should be changed to be an alias.

**Comment by Oghenebrume50** [comment]
it actually works without changing the line though

**Comment by AlbertoPdRF** [comment]
Fixed in #18.
